### ISSUE TITLE
Optional support for headers such as x-forwarded-proto

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-redirect-to-https#2]
Hosting providers like Fly handle HTTPS for you but cause the incoming request to have `"scheme": "http"` in the ASGI context.

They suggest instead trusting the `x-forwarded-proto` header, see https://fly.io/blog/always-be-connecting-with-https/

For security reasons this should require additional configuration.

**Comment by simonw** [comment]
Relevant code: https://github.com/simonw/datasette-redirect-to-https/blob/0ff35eafe9d8af40cadd0259dd8a6d7dd44fa366/datasette_redirect_to_https/__init__.py#L11-L13

**Comment by simonw** [comment]
Potential design for `metadata.yml`:

```yaml
plugins:
  datasette-redirect-to-https:
    if_header:
      x-forwarded-proto: http
```
This could then allow implementation of an OR rule, but that seems vanishingly unlikely to be useful.

I think the syntax is pretty clean though.

Alternative, if only supporting `x-forwarded-proto` and no other headers, could be:

```yaml
plugins:
  datasette-redirect-to-https:
    respect-x-forwarded-proto: true
```

I think I like the first option more, aesthetically.
